version: 2

sources:
  - name: pagila
    database: MODERN_DATA_DB
    schema: raw_pagila
    config:
      loaded_at_field: _airbyte_extracted_at
      freshness:
        warn_after: {count: 24, period: hour}
        error_after: {count: 48, period: hour}
    tables:
      - name: actor
      - name: film
      - name: category
      - name: rental
      - name: customer
      - name: inventory
      - name: payment
      - name: address
      - name: city
      - name: film_actor   
      - name: film_category

  - name: sakila
    database: MODERN_DATA_DB
    schema: raw_sakila
    config:
      loaded_at_field: _airbyte_extracted_at
      freshness:
        warn_after: {count: 24, period: hour}
        error_after: {count: 48, period: hour}
    tables:
      - name: actor
      - name: film
      - name: category
      - name: rental
      - name: customer
      - name: inventory
      - name: payment
      - name: address
      - name: city
      - name: film_actor 
      - name: film_category